[project]
name = "fig-detect-yolo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.12.0",
    "pymupdf>=1.26.5",
    "ultralytics>=8.3.209",
]
